build:
  image: registry.aliyuncs.com/ndpuz-img/nginx:latest
  commands:
    - /etc/init.d/nginx configtest
  when:
    branch: [staging, master]
publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: ndpuz-img/nginx
    tag: latest
    file: Dockerfile
    mirror: https://kpm1lqaf.mirror.aliyuncs.com
    when:
      branch: ndpuz